### ISSUE TITLE
Functions are missing ?

### ISSUE THREAD

**Issue by juzimmer** [mix1009/desktop_window#38]
Seems for me I'm missing some functions like setBorders() ?

![functions](https://user-images.githubusercontent.com/30728491/145906733-233c49bc-a317-48e7-979e-ea54e1ae544c.jpg)

**Comment by juzimmer** [comment]
Also getWindowSize() is returning zeros

**Comment by alex-bluetrain** [comment]
same here, I just compared the src code from the package and the repository.

it seems the package was built using an old commit, probably 54b6f82b162c25f6405c87d977a1d68dc0075c97 from March 9

**Comment by alex-bluetrain** [comment]
as a workaround, change your pubspec.yaml to be like this:

```
  desktop_window: 
    git:
      url: https://github.com/mix1009/desktop_window
      ref: c0800a77477141ce7d1ad3080db5909fcce0d520
```
